user_admin_commande:
    resource: "@AdminBundle/Resources/config/commande.yml"
    prefix:   /commande

admin_homepage:
    path:     /back
    defaults: { _controller: AdminBundle:Default:back }
livreur_ajout:
    path:     /ajoutlivreur
    defaults: { _controller: AdminBundle:Livreur:ajoutLivreur }
show_Livreur:
    path:     /showlivreur
    defaults: { _controller: AdminBundle:Livreur:showLivreur }
livreur_ajoutMob:
    path:     /ajoutlivreurMob
    defaults: { _controller: AdminBundle:Livreur:ajoutLivreurMob }
show_LivreurMob:
    path:     /showlivreurMob
    defaults: { _controller: AdminBundle:Livreur:showLivreurMob }
remove_Livreur:
    path:     /remove_Livreur
    defaults: { _controller: AdminBundle:Livreur:RemoveLivreur }
update_Livreur:
    path:     /update_Livreur/{id}
    defaults: { _controller: AdminBundle:Livreur:updateLivreur }
fournisseur_ajout:
    path:     /ajoutfournisseur
    defaults: { _controller: AdminBundle:Fournisseur:ajoutFournisseur }
show_Fournisseur:
    path:     /showfournisseur
    defaults: { _controller: AdminBundle:Fournisseur:showFournisseur }
remove_Fournisseur:
    path:     /remove_Fournisseur
    defaults: { _controller: AdminBundle:Fournisseur:RemoveFournisseur }
update_Fournisseur:
    path:     /update_Fournisseur/{id}
    defaults: { _controller: AdminBundle:Fournisseur:updateFournisseur }
fournisseur_mail:
    path:     /composemail/{id}
    defaults: { _controller: AdminBundle:Fournisseur:mail }
fournisseur_ajoutMob:
    path:     /ajoutfournisseurMob
    defaults: { _controller: AdminBundle:Fournisseur:ajoutFournisseurMobile }
show_FournisseurMob:
    path:     /showfournisseurMob
    defaults: { _controller: AdminBundle:Fournisseur:showFournisseurMobile }

find_livreur:
    path:     /livreurs/find/{id}
    defaults: { _controller: AdminBundle:Livreur:find}
searchlivreur:
    path:     /searchlivreur/{nom}
    defaults: { _controller: AdminBundle:Livreur:SearchByNom}
update:
    path:     /updatefr
    defaults: { _controller: AdminBundle:Fournisseur:updateFournisseurMobile}
update_liv:
    path:     /updateliv/{id}
    defaults: { _controller: AdminBundle:Livreur:updateLivreurMobile}
deleteLiv:
    path:     /deleteliv
    defaults: { _controller: AdminBundle:Livreur:deleteLivreurMobile}
update_fsr:
    path:     /updatefsr/{id}
    defaults: { _controller: AdminBundle:Fournisseur:updateFournisseurMobile}
deletefsr:
    path:     /deletefsr
    defaults: { _controller: AdminBundle:Fournisseur:deleteFournisseurMobile}
searchfsr:
    path:     /searchfsr/{nomSociete}
    defaults: { _controller: AdminBundle:Fournisseur:SearchByNomSociete}


