<?php

namespace EmplacementBundle\Repository;

/**
 * AlleeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlleeRepository extends \Doctrine\ORM\EntityRepository
{

    public function myEmp()
    {




    }
}
