<?php

namespace EmplacementBundle\Repository;

/**
 * TraveeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraveeRepository extends \Doctrine\ORM\EntityRepository
{
}
